### ISSUE TITLE
Only noise after sampling in example notebook

### ISSUE THREAD

**Issue by nfsrules** [LuChengTHU/dpm-solver#2]
[example.txt](https://github.com/LuChengTHU/dpm-solver/files/9373699/example.txt)

Hi, thanks for this significant contribution!

I'm trying to get familiarized with the API following the example you've provided on the readme. 

However, so far I only get random noise after sampling. Am I doing something wrong?

Best regards

**Comment by LuChengTHU** [comment]
Hi @nfsrules ,

Thanks for your interest! I've read your example code briefly. It seems that you forget to apply the inverse data transformation, e.g.:

https://github.com/LuChengTHU/dpm-solver/blob/main/example_pytorch/runners/diffusion.py#L410

Specifically, for diffusion models trained on images, the image data ([0, 255]^D) needs firstly to be transformed to [-1,1]^D. So the "sample" (x_0 in DPMs, i.e. output of DPM-Solver) is actually the data with the range [-1,1]^D, and you need further transform it to the image range [0,255]^D.

**Comment by nfsrules** [comment]
[example_updated.txt](https://github.com/LuChengTHU/dpm-solver/files/9376723/example_updated.txt)
Thank you!
I've checked and the output after sampling was already in the 0-255 range, that's odd. I've tested with the inverse transform with no success.

**Comment by LuChengTHU** [comment]
Hi @nfsrules 

Sorry for the misleading in the last response. The inverse_transform is to let [-1,1]^D -> [0,1]^D, and you need to further transform it to [0, 255]^D.

For example, in https://github.com/LuChengTHU/dpm-solver/blob/main/example_pytorch/runners/diffusion.py#L421

The `torchvision.utils.save_image` does the following thing:

x = x.mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to("cpu", torch.uint8).numpy()

==================

In addition, your code has another bug: you need to use `torch.randn`(which is the standard normal distribution) to sample x_T, rather than `torch.rand`(which is uniform distribution).

**Comment by nfsrules** [comment]
That did the trick! Thank you. I'll close the issue
