### ISSUE TITLE
VESDE support?

### ISSUE THREAD

**Issue by yuanzhi-zhu** [LuChengTHU/dpm-solver#5]
Thanks for you great work! This DPM solver can speed up VPSDE sampling quite a lot.

Notice that VESDE has $f(t)=0$, and $\sigma_t$ with exponential structure, it should be easier to get a _exponentially weighted integral_ of $\epsilon_\theta(x_t,t)$: 
$\int_{\mu_s}^{\mu_t} \sigma_{min}e^{\mu} \hat{\epsilon_\theta} (x_\mu,\mu) d \mu$  
which is equivalent to the 2nd term on the rhs of (3.4) in the paper.

With minor modification on the NoiseScheduleVP (set $\alpha_t = 1$ for all formulas in the paper and calculate the inverse lambda), I expect the solver can be adapted to VESDE.

However, when I try to apply it with VESDE, I can't get proper results (still pure noise).

Have you tried VESDE before and encounter similar problem?
Or do I get something wrong here? 

Ps: With adapter DPM solver, I get $t\approx 1$ in the first few steps (which is what we expect for VESDE as mentioned in  https://github.com/yang-song/score_sde_pytorch/issues/28), but still get $x_0$ is pure noise with very large variance)

**Comment by LuChengTHU** [comment]
Hi @yuanzhi-zhu ,

In my experience, the diffusion ODEs with the VESDE in Yang Song's "score_sde" repo are much worse than diffusion SDEs (e.g. The samples by 1000-step DDIM are much worse than those by 1000-step DDPM). DPM-Solver can still accelerate the sampling procedure, but as the converged solution is bad, the samples with few steps are also bad. Recent work[1] points out that the training in VESDE needs parameterizations to reduce the training variance, and I believe DPM-Solver can accelerate their pre-trained VESDE models. However, as they didn't release the code yet, I'm not 100% sure.

[1] Elucidating the Design Space of Diffusion-Based Generative Models. https://arxiv.org/abs/2206.00364

However, the pure noise problem you met is likely to be a bug. (For example, have you mistaken the score model $s_theta$ in Yang Song's repo with the noise prediction model $\epsilon_\theta$? They are different models.) Nevertheless, I will try to implement a VESDE version and update the repo as soon as possible. Here I also provide a quick solution for it:

Note that according to [2], **all types of diffusion models are equivalent**. (I believe that few researchers know this conclusion). Therefore, you can convert any DPMs to the VP type and use our method. For example, denote that $p(x_t | x_0) = N(\alpha_t x_0, \sigma_t^2 I)$, we can convert such process to the VP type by letting

$y_t = x_t / (\sqrt{\alpha_t^2 + \sigma_t^2})$

thus $y_t$ is a VP-type diffusion process. We can further modify the noise prediction model $\epsilon_\theta$ from $x_t$ to $y_t$ by the chain rule of score function (see [2] for details) and then get a VP-type diffusion ODE w.r.t. $y_t$. 

[2] Variational Diffusion Models. https://arxiv.org/abs/2107.00630

**Comment by yuanzhi-zhu** [comment]
Massive thanks for your insightful reply and suggestions, Cheng Lu!!

Actually, I did use the score function, I tested it with VPSDE ckpt from Yang Song, it's good. But it performed poorly with the VESDE ckpt. I will investigate further into my code and also try to convert the sampling process into VPSDE follow your suggestion. (I see you are a master of substitution :p)

Also, I am looking forward to your update of this repo on VESDE!!

I have an irreverent question here: it seems to me that all the accelerating sampling methods come at a price of slightly image quality, comparing to sampling the full training trajectory (In this case the DPM-solver is one of the best methods to balance the sampling speed and quality).  Does this understanding make sense?

**Comment by LuChengTHU** [comment]
Hi @yuanzhi-zhu 

About the trade-off between sampling quality and speed:

In fact, you can understand all the training-free sampling methods of DPMs as discretizing either diffusion SDEs (such as the ancestral sampling of the original DDPM) or diffusion ODEs (such as DDIM or DPM-Solver). Therefore, the best sample quality is the best of the converged solutions of diffusion SDEs or diffusion ODEs. 

For DPM-Solver, it is a fast solver for diffusion ODEs, so it can obtain an almost converged solution in only around 20 steps and a converged solution in only around 50 steps. Compared with the 1000-step DDIM, the 50-step DPM-Solver has the same sample quality but a much faster speed. Therefore, I believe the 50-step DPM-Solver may replace the 1000-step DDIM in the future.

However, as diffusion SDEs and diffusion ODEs are two different distributions, the best quality of diffusion ODEs may have a gap from that of diffusion SDEs. So there exists a possibility that the converged solution by DPM-Solver is still slightly worse than the 1000-step DDPM (which is the converged solution of diffusion SDEs). We may address this problem by improving the training techniques for diffusion ODEs, but it is not something DPM-Solver cares about (because it is a training-free algorithm for inference).

**Comment by yuanzhi-zhu** [comment]
Hi @LuChengTHU,

Thanks again for your insightful discussion, I get it now that the DPM solver can have the same generation quality comparing to other ODE solving methods due to the convergence order guarantee. (And I guess the gap between ODE and SDE may originate from the randomness.)

**Comment by sarvghotra** [comment]
@yuanzhi-zhu could you use DPM-solver successfully with a VE SDE model?

**Comment by yuanzhi-zhu** [comment]
> @yuanzhi-zhu could you use DPM-solver successfully with a VE SDE model?

Hey, not really as we switched to the VP form diffusion models.

But @LuChengTHU may have some update on this?

**Comment by sarvghotra** [comment]
JFYI, I couldn't get good results for VE SDE case.
